[tools]
node = "24.18.0"
npm = "11.16.0"

[tasks.build]
run = 'npm run build'

[tasks.clean]
run = 'rm -rf node_modules dist package-lock.json'

[tasks.dev]
run = 'npm run dev'

[tasks.install]
run = 'npm install'