---
project_name: portfolio
docker_root: /opt/docker
docker_apps_dir: "{{ docker_root }}/apps"
docker_network_name: proxy
docker_compose_dir: "{{ docker_root }}/compose"

portfolio_compose_dir: "{{ docker_compose_dir }}/portfolio"
portfolio_compose_file: "{{ portfolio_compose_dir }}/compose.yaml"
portfolio_image: ghcr.io/teopartesi/portfolio
portfolio_image_tag: "1.1.1"
portfolio_domain: teopartesi.fr
portfolio_port: 3000

traefik_compose_dir: "{{ docker_compose_dir }}/traefik"
traefik_compose_file: "{{ traefik_compose_dir }}/compose.yaml"
traefik_image: traefik:v3.7.8
traefik_acme_email: teopartesi@gmail.com
traefik_acme_file: "{{ docker_root }}/volumes/traefik/acme.json"
